### ISSUE TITLE
Webp - 007_Выводим контент в шаблоне.md

### ISSUE THREAD

**Issue by Aharito** [0test/lessons-evolution-blog#7]
В уроке "007_Выводим контент в шаблоне.md" предлагается сделать несколько новостей, и приводится пример сайта веселых новостей. Но там картинки в формате `webp`. 

Попытка скачать их, а затем вставить в пост сразу же вызовет у некоторых обучающихся доп. **трудности**.

Нужно либо сменить пример, где картинки будут в простом `jpg`, либо все же как-то решать вопрос с `webp` у нас в Эво.

1) Загрузчик изображений даже **не позволяет** их грузить.

![image](https://user-images.githubusercontent.com/6253807/219611871-596e551f-bcdf-477c-90b1-a48ea2ed0d14.png)

2) Нужно как минимум **дать пример**, чтобы дописали `webp` в разрешённые, ну или уж сделать такую настройку по дефолту.

![image](https://user-images.githubusercontent.com/6253807/219612112-6b2b49c9-0ae6-423d-b544-51f41236fc16.png)

3) Но даже после указания `webp` как возможного к загрузке, он хоть и загружается, но отображается в виде **пустого превью**.

![image](https://user-images.githubusercontent.com/6253807/219613013-96a5fa47-6d3c-4088-81e4-8be9ffa3a663.png)

Так происходит несмотря на то, что моя Windows **настроена** для отображения `webp`, вот как выглядит у меня в родных окнах винды:

![image](https://user-images.githubusercontent.com/6253807/219613513-fff2f459-95ec-4971-9e2a-93e89196fbd5.png)

**Comment by 0test** [comment]
Боюсь, к блогу это отношения не имеет, в Эву закинем ишью.
